// Code generated by MockGen. DO NOT EDIT.
// Source: email.go
//
// Generated by this command:
//
//	mockgen -source=email.go -package=ntfy -destination=email_mock_test.go -typed
//

// Package ntfy is a generated GoMock package.
package ntfy

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailStore is a mock of EmailStore interface.
type MockEmailStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailStoreMockRecorder
	isgomock struct{}
}

// MockEmailStoreMockRecorder is the mock recorder for MockEmailStore.
type MockEmailStoreMockRecorder struct {
	mock *MockEmailStore
}

// NewMockEmailStore creates a new mock instance.
func NewMockEmailStore(ctrl *gomock.Controller) *MockEmailStore {
	mock := &MockEmailStore{ctrl: ctrl}
	mock.recorder = &MockEmailStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailStore) EXPECT() *MockEmailStoreMockRecorder {
	return m.recorder
}

// ClaimEmails mocks base method.
func (m *MockEmailStore) ClaimEmails(ctx context.Context, claim EmailClaim) ([]EmailCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimEmails", ctx, claim)
	ret0, _ := ret[0].([]EmailCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimEmails indicates an expected call of ClaimEmails.
func (mr *MockEmailStoreMockRecorder) ClaimEmails(ctx, claim any) *MockEmailStoreClaimEmailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimEmails", reflect.TypeOf((*MockEmailStore)(nil).ClaimEmails), ctx, claim)
	return &MockEmailStoreClaimEmailsCall{Call: call}
}

// MockEmailStoreClaimEmailsCall wrap *gomock.Call
type MockEmailStoreClaimEmailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailStoreClaimEmailsCall) Return(arg0 []EmailCandidate, arg1 error) *MockEmailStoreClaimEmailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailStoreClaimEmailsCall) Do(f func(context.Context, EmailClaim) ([]EmailCandidate, error)) *MockEmailStoreClaimEmailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailStoreClaimEmailsCall) DoAndReturn(f func(context.Context, EmailClaim) ([]EmailCandidate, error)) *MockEmailStoreClaimEmailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PurgeEmailRecords mocks base method.
func (m *MockEmailStore) PurgeEmailRecords(ctx context.Context, limit int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeEmailRecords", ctx, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeEmailRecords indicates an expected call of PurgeEmailRecords.
func (mr *MockEmailStoreMockRecorder) PurgeEmailRecords(ctx, limit any) *MockEmailStorePurgeEmailRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeEmailRecords", reflect.TypeOf((*MockEmailStore)(nil).PurgeEmailRecords), ctx, limit)
	return &MockEmailStorePurgeEmailRecordsCall{Call: call}
}

// MockEmailStorePurgeEmailRecordsCall wrap *gomock.Call
type MockEmailStorePurgeEmailRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailStorePurgeEmailRecordsCall) Return(arg0 int64, arg1 error) *MockEmailStorePurgeEmailRecordsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailStorePurgeEmailRecordsCall) Do(f func(context.Context, int) (int64, error)) *MockEmailStorePurgeEmailRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailStorePurgeEmailRecordsCall) DoAndReturn(f func(context.Context, int) (int64, error)) *MockEmailStorePurgeEmailRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecordEmails mocks base method.
func (m *MockEmailStore) RecordEmails(ctx context.Context, record EmailRecord) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordEmails", ctx, record)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordEmails indicates an expected call of RecordEmails.
func (mr *MockEmailStoreMockRecorder) RecordEmails(ctx, record any) *MockEmailStoreRecordEmailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEmails", reflect.TypeOf((*MockEmailStore)(nil).RecordEmails), ctx, record)
	return &MockEmailStoreRecordEmailsCall{Call: call}
}

// MockEmailStoreRecordEmailsCall wrap *gomock.Call
type MockEmailStoreRecordEmailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailStoreRecordEmailsCall) Return(arg0 int64, arg1 error) *MockEmailStoreRecordEmailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailStoreRecordEmailsCall) Do(f func(context.Context, EmailRecord) (int64, error)) *MockEmailStoreRecordEmailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailStoreRecordEmailsCall) DoAndReturn(f func(context.Context, EmailRecord) (int64, error)) *MockEmailStoreRecordEmailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAddressBook is a mock of AddressBook interface.
type MockAddressBook struct {
	ctrl     *gomock.Controller
	recorder *MockAddressBookMockRecorder
	isgomock struct{}
}

// MockAddressBookMockRecorder is the mock recorder for MockAddressBook.
type MockAddressBookMockRecorder struct {
	mock *MockAddressBook
}

// NewMockAddressBook creates a new mock instance.
func NewMockAddressBook(ctrl *gomock.Controller) *MockAddressBook {
	mock := &MockAddressBook{ctrl: ctrl}
	mock.recorder = &MockAddressBookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressBook) EXPECT() *MockAddressBookMockRecorder {
	return m.recorder
}

// AddressOf mocks base method.
func (m *MockAddressBook) AddressOf(ctx context.Context, recipient string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressOf", ctx, recipient)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddressOf indicates an expected call of AddressOf.
func (mr *MockAddressBookMockRecorder) AddressOf(ctx, recipient any) *MockAddressBookAddressOfCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressOf", reflect.TypeOf((*MockAddressBook)(nil).AddressOf), ctx, recipient)
	return &MockAddressBookAddressOfCall{Call: call}
}

// MockAddressBookAddressOfCall wrap *gomock.Call
type MockAddressBookAddressOfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAddressBookAddressOfCall) Return(address string, ok bool, err error) *MockAddressBookAddressOfCall {
	c.Call = c.Call.Return(address, ok, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAddressBookAddressOfCall) Do(f func(context.Context, string) (string, bool, error)) *MockAddressBookAddressOfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAddressBookAddressOfCall) DoAndReturn(f func(context.Context, string) (string, bool, error)) *MockAddressBookAddressOfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEmailTemplate is a mock of EmailTemplate interface.
type MockEmailTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockEmailTemplateMockRecorder
	isgomock struct{}
}

// MockEmailTemplateMockRecorder is the mock recorder for MockEmailTemplate.
type MockEmailTemplateMockRecorder struct {
	mock *MockEmailTemplate
}

// NewMockEmailTemplate creates a new mock instance.
func NewMockEmailTemplate(ctrl *gomock.Controller) *MockEmailTemplate {
	mock := &MockEmailTemplate{ctrl: ctrl}
	mock.recorder = &MockEmailTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailTemplate) EXPECT() *MockEmailTemplateMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockEmailTemplate) Render(ctx context.Context, batch EmailBatch) (EmailContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, batch)
	ret0, _ := ret[0].(EmailContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockEmailTemplateMockRecorder) Render(ctx, batch any) *MockEmailTemplateRenderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockEmailTemplate)(nil).Render), ctx, batch)
	return &MockEmailTemplateRenderCall{Call: call}
}

// MockEmailTemplateRenderCall wrap *gomock.Call
type MockEmailTemplateRenderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailTemplateRenderCall) Return(arg0 EmailContent, arg1 error) *MockEmailTemplateRenderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailTemplateRenderCall) Do(f func(context.Context, EmailBatch) (EmailContent, error)) *MockEmailTemplateRenderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailTemplateRenderCall) DoAndReturn(f func(context.Context, EmailBatch) (EmailContent, error)) *MockEmailTemplateRenderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailer) Send(ctx context.Context, message EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailerMockRecorder) Send(ctx, message any) *MockMailerSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailer)(nil).Send), ctx, message)
	return &MockMailerSendCall{Call: call}
}

// MockMailerSendCall wrap *gomock.Call
type MockMailerSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMailerSendCall) Return(arg0 error) *MockMailerSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMailerSendCall) Do(f func(context.Context, EmailMessage) error) *MockMailerSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMailerSendCall) DoAndReturn(f func(context.Context, EmailMessage) error) *MockMailerSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEmailFilter is a mock of EmailFilter interface.
type MockEmailFilter struct {
	ctrl     *gomock.Controller
	recorder *MockEmailFilterMockRecorder
	isgomock struct{}
}

// MockEmailFilterMockRecorder is the mock recorder for MockEmailFilter.
type MockEmailFilterMockRecorder struct {
	mock *MockEmailFilter
}

// NewMockEmailFilter creates a new mock instance.
func NewMockEmailFilter(ctrl *gomock.Controller) *MockEmailFilter {
	mock := &MockEmailFilter{ctrl: ctrl}
	mock.recorder = &MockEmailFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailFilter) EXPECT() *MockEmailFilterMockRecorder {
	return m.recorder
}

// ShouldEmail mocks base method.
func (m *MockEmailFilter) ShouldEmail(ctx context.Context, n Notification) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldEmail", ctx, n)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldEmail indicates an expected call of ShouldEmail.
func (mr *MockEmailFilterMockRecorder) ShouldEmail(ctx, n any) *MockEmailFilterShouldEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldEmail", reflect.TypeOf((*MockEmailFilter)(nil).ShouldEmail), ctx, n)
	return &MockEmailFilterShouldEmailCall{Call: call}
}

// MockEmailFilterShouldEmailCall wrap *gomock.Call
type MockEmailFilterShouldEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailFilterShouldEmailCall) Return(arg0 bool, arg1 error) *MockEmailFilterShouldEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailFilterShouldEmailCall) Do(f func(context.Context, Notification) (bool, error)) *MockEmailFilterShouldEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailFilterShouldEmailCall) DoAndReturn(f func(context.Context, Notification) (bool, error)) *MockEmailFilterShouldEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
