// Code generated by MockGen. DO NOT EDIT.
// Source: realtime.go
//
// Generated by this command:
//
//	mockgen -source=realtime.go -package=ntfy -destination=realtime_mock_test.go -typed
//

// Package ntfy is a generated GoMock package.
package ntfy

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroadcaster is a mock of Broadcaster interface.
type MockBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcasterMockRecorder
	isgomock struct{}
}

// MockBroadcasterMockRecorder is the mock recorder for MockBroadcaster.
type MockBroadcasterMockRecorder struct {
	mock *MockBroadcaster
}

// NewMockBroadcaster creates a new mock instance.
func NewMockBroadcaster(ctrl *gomock.Controller) *MockBroadcaster {
	mock := &MockBroadcaster{ctrl: ctrl}
	mock.recorder = &MockBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcaster) EXPECT() *MockBroadcasterMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockBroadcaster) Broadcast(ctx context.Context, signals []Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", ctx, signals)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockBroadcasterMockRecorder) Broadcast(ctx, signals any) *MockBroadcasterBroadcastCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockBroadcaster)(nil).Broadcast), ctx, signals)
	return &MockBroadcasterBroadcastCall{Call: call}
}

// MockBroadcasterBroadcastCall wrap *gomock.Call
type MockBroadcasterBroadcastCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBroadcasterBroadcastCall) Return(arg0 error) *MockBroadcasterBroadcastCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBroadcasterBroadcastCall) Do(f func(context.Context, []Signal) error) *MockBroadcasterBroadcastCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBroadcasterBroadcastCall) DoAndReturn(f func(context.Context, []Signal) error) *MockBroadcasterBroadcastCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Listen mocks base method.
func (m *MockBroadcaster) Listen(ctx context.Context, deliver func(Signal), ready func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx, deliver, ready)
	ret0, _ := ret[0].(error)
	return ret0
}

// Listen indicates an expected call of Listen.
func (mr *MockBroadcasterMockRecorder) Listen(ctx, deliver, ready any) *MockBroadcasterListenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockBroadcaster)(nil).Listen), ctx, deliver, ready)
	return &MockBroadcasterListenCall{Call: call}
}

// MockBroadcasterListenCall wrap *gomock.Call
type MockBroadcasterListenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBroadcasterListenCall) Return(arg0 error) *MockBroadcasterListenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBroadcasterListenCall) Do(f func(context.Context, func(Signal), func()) error) *MockBroadcasterListenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBroadcasterListenCall) DoAndReturn(f func(context.Context, func(Signal), func()) error) *MockBroadcasterListenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
