// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -package=notify -destination=store_mock_test.go -typed
//

// Package notify is a generated GoMock package.
package notify

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStore) Close(ctx context.Context, req CloseRequest, at time.Time, ids IDGenerator) (CloseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, req, at, ids)
	ret0, _ := ret[0].(CloseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close(ctx, req, at, ids any) *MockStoreCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close), ctx, req, at, ids)
	return &MockStoreCloseCall{Call: call}
}

// MockStoreCloseCall wrap *gomock.Call
type MockStoreCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCloseCall) Return(arg0 CloseResult, arg1 error) *MockStoreCloseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCloseCall) Do(f func(context.Context, CloseRequest, time.Time, IDGenerator) (CloseResult, error)) *MockStoreCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCloseCall) DoAndReturn(f func(context.Context, CloseRequest, time.Time, IDGenerator) (CloseResult, error)) *MockStoreCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountActive mocks base method.
func (m *MockStore) CountActive(ctx context.Context, recipient string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx, recipient)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockStoreMockRecorder) CountActive(ctx, recipient any) *MockStoreCountActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockStore)(nil).CountActive), ctx, recipient)
	return &MockStoreCountActiveCall{Call: call}
}

// MockStoreCountActiveCall wrap *gomock.Call
type MockStoreCountActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCountActiveCall) Return(arg0 int64, arg1 error) *MockStoreCountActiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCountActiveCall) Do(f func(context.Context, string) (int64, error)) *MockStoreCountActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCountActiveCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockStoreCountActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, recipient, id string) (Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, recipient, id)
	ret0, _ := ret[0].(Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, recipient, id any) *MockStoreGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, recipient, id)
	return &MockStoreGetCall{Call: call}
}

// MockStoreGetCall wrap *gomock.Call
type MockStoreGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetCall) Return(arg0 Notification, arg1 error) *MockStoreGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetCall) Do(f func(context.Context, string, string) (Notification, error)) *MockStoreGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetCall) DoAndReturn(f func(context.Context, string, string) (Notification, error)) *MockStoreGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockStore) Insert(ctx context.Context, subject string, insertions []Insertion) (InsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, subject, insertions)
	ret0, _ := ret[0].(InsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockStoreMockRecorder) Insert(ctx, subject, insertions any) *MockStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStore)(nil).Insert), ctx, subject, insertions)
	return &MockStoreInsertCall{Call: call}
}

// MockStoreInsertCall wrap *gomock.Call
type MockStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreInsertCall) Return(arg0 InsertResult, arg1 error) *MockStoreInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreInsertCall) Do(f func(context.Context, string, []Insertion) (InsertResult, error)) *MockStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreInsertCall) DoAndReturn(f func(context.Context, string, []Insertion) (InsertResult, error)) *MockStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context, q ListQuery) (Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].(Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx, q any) *MockStoreListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx, q)
	return &MockStoreListCall{Call: call}
}

// MockStoreListCall wrap *gomock.Call
type MockStoreListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListCall) Return(arg0 Page, arg1 error) *MockStoreListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListCall) Do(f func(context.Context, ListQuery) (Page, error)) *MockStoreListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListCall) DoAndReturn(f func(context.Context, ListQuery) (Page, error)) *MockStoreListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkAllRead mocks base method.
func (m *MockStore) MarkAllRead(ctx context.Context, recipient string, through, at time.Time) (MarkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, recipient, through, at)
	ret0, _ := ret[0].(MarkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockStoreMockRecorder) MarkAllRead(ctx, recipient, through, at any) *MockStoreMarkAllReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockStore)(nil).MarkAllRead), ctx, recipient, through, at)
	return &MockStoreMarkAllReadCall{Call: call}
}

// MockStoreMarkAllReadCall wrap *gomock.Call
type MockStoreMarkAllReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreMarkAllReadCall) Return(arg0 MarkResult, arg1 error) *MockStoreMarkAllReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreMarkAllReadCall) Do(f func(context.Context, string, time.Time, time.Time) (MarkResult, error)) *MockStoreMarkAllReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreMarkAllReadCall) DoAndReturn(f func(context.Context, string, time.Time, time.Time) (MarkResult, error)) *MockStoreMarkAllReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkRead mocks base method.
func (m *MockStore) MarkRead(ctx context.Context, recipient string, ids []string, at time.Time) (MarkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, recipient, ids, at)
	ret0, _ := ret[0].(MarkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockStoreMockRecorder) MarkRead(ctx, recipient, ids, at any) *MockStoreMarkReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockStore)(nil).MarkRead), ctx, recipient, ids, at)
	return &MockStoreMarkReadCall{Call: call}
}

// MockStoreMarkReadCall wrap *gomock.Call
type MockStoreMarkReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreMarkReadCall) Return(arg0 MarkResult, arg1 error) *MockStoreMarkReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreMarkReadCall) Do(f func(context.Context, string, []string, time.Time) (MarkResult, error)) *MockStoreMarkReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreMarkReadCall) DoAndReturn(f func(context.Context, string, []string, time.Time) (MarkResult, error)) *MockStoreMarkReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prune mocks base method.
func (m *MockStore) Prune(ctx context.Context, req PruneRequest) (PruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, req)
	ret0, _ := ret[0].(PruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockStoreMockRecorder) Prune(ctx, req any) *MockStorePruneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockStore)(nil).Prune), ctx, req)
	return &MockStorePruneCall{Call: call}
}

// MockStorePruneCall wrap *gomock.Call
type MockStorePruneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorePruneCall) Return(arg0 PruneResult, arg1 error) *MockStorePruneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorePruneCall) Do(f func(context.Context, PruneRequest) (PruneResult, error)) *MockStorePruneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorePruneCall) DoAndReturn(f func(context.Context, PruneRequest) (PruneResult, error)) *MockStorePruneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
